### ISSUE TITLE
재구조화

### ISSUE THREAD

**Issue by PleahMaCaka** [project-ait/server#27]
## Summary
- Reformt/Rewrite whole logics

## Task
- [x] Disable Bart and replace to LLaMA 2 (if over the limits)
- [ ] Service is not included routers
- [x] Some queued reformats
- [x] Decreases memory usages 
- [x] ~~Lazy env loader~~ *canceled*

**Comment by PleahMaCaka** [comment]
✅ All solved.
